---
title: "ISYE6414 Project - Exploring Linear Trends and Correlations"
output: html_notebook
---

```{r}
data = read.csv("../Data/Life-Expectancy-Data-Updated.csv")

# drop some columns
data = data[-c(1,20)]
# data = subset(data, select = -c(data$Country, data$Economy_status_Developing))
# country is not needed for analysis
# economy_status_developing is just 1 - economy_status_developed

names(data) = c("Region", "Year", "Infant_deaths", "Under_five_deaths", 
                "Adult mortality", "Alcohol consumption", "Hepatitis_B", 
                "Measles", "BMI", "Polio", "Diphtheria", "Incidents_HIV", 
                "GDP_per_capita", "Population_min", 
                "Thinness_ten_nineteen_years", "Thinness_five_nine_years",
                "Schooling", "Economy_status_Developed", "Life_expectancy")
attach(data)
Region <- as.factor(Region)
Economy_status_Developed <- as.factor(Economy_status_Developed)
```
```{r}
plot(data[,c(19,1:3)])
```
```{r}
plot(data[,c(19,4:6)])
```
```{r}
plot(data[,c(19,7:9)])
```
```{r}
plot(data[,c(19,10:12)])
```
```{r}
plot(data[,c(19,13:15)])
```
```{r}
plot(data[,c(19,16:18)])
```

```{r}
library(corrplot)
corrplot(cor(data[-c(1,2,18)]), type="lower", method="square",
  tl.col="black", tl.cex = 0.9, number.cex=0.8)
```






